---
- name: CI Testing Playbook
  hosts: all

  vars:
    scl_wrappers:
      - {collection: 'rh-ruby23'}
      - {collection: 'rh-ruby23', command: 'ruby'}
      - {collection: 'rh-python35'}
      - {collection: 'rh-python35', command: 'python'}
    scl_packages:
      - {name: 'rh-ruby23', state: 'latest'}
      - {name: 'rh-python35', state: 'latest'}
    scl_ruby_gems:
      - {
        ruby_ver: 'rh-ruby23',
        name: 'fast_github',
        state: 'present',
      }
    scl_python_pips:
      - {
        python_ver: 'rh-python35',
        name: 'travis',
        state: 'present',
      }

  roles:
    - {role: ansible-role-scl}

